# -*- coding: utf-8 -*-
"""3-yolov5.ipynb의 사본의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBqTzo8rS1sIx2SyDtyZ8yugMuqyhGbq
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
!pip install -qr yolov5/requirements.txt  # install dependencies (ignore errors)
# %cd yolov5

import torch
from IPython.display import Image, clear_output  # to display images
from utils.google_utils import gdrive_download  # to download models/datasets

!python detect.py --source ../elephant2.png

!python detect.py --source ../giraffe.png

from google.colab import drive
drive.mount('/content/drive')

!python detect.py --source ../20210608.mp4